FROM alpine:latest

WORKDIR /app

COPY pocketbase /app/pocketbase
COPY pb_data /app/pb_data
COPY pb_migrations /app/pb_migrations

RUN chmod 755 /app/pocketbase

CMD ["sh", "-c", "./pocketbase serve --http=0.0.0.0:$PORT"]
